project:
  type: website

website:
  title: "Math377FinalProject"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: journal
    css: styles.css````````````````````````
    toc: true

editor: visual

